kind: pipeline
name: test

steps:
- name: build
  image: golang
  commands:
    - echo -n "Hello"

steps:
- name: publish  
  image: plugins/gcr
  settings:
    repo: arenstar/docker-skeleton
    tags: latest
    registry: eu.gcr.io
    json_key:
      from_secret: google-credentials
