kind: pipeline
name: test

steps:
- name: build
  image: golang
  commands:
    - echo -n "Hello"

steps:
- name: publish  
  image: plugins/gcr
  tags:
  - ${DRONE_BRANCH}
  - ${DRONE_COMMIT_SHA}
  - ${DRONE_BUILD_NUMBER}
  settings:
    repo: primeval-falcon-186518/docker-skeleton
    tags: latest
    registry: eu.gcr.io
    json_key:
      from_secret: google-credentials
