kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: golang
  commands:
    - echo -n "Hello"

steps:
- name: publish  
  image: plugins/gcr
  environment:
    google-credentials:
      from_secret: google-credentials
  settings:
    repo: primeval-falcon-186518/docker-skeleton
    tags:
    - ${DRONE_BRANCH}
    - ${DRONE_COMMIT_SHA}
    - ${DRONE_BUILD_NUMBER}
    debug: true
    registry: eu.gcr.io
    json_key:
      from_secret: google-credentials
  when:
    event: push
    branch: master

---
kind: secret
name: google-credentials
get:
  path: google-credentials
  name: keyfile
